version: "3.7"

services:
  authenticated-api:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0
    ports:
      - 9000:8000
      - 10002:10002
    volumes:
      - ./:/usr/src/app
    environment:
      - DEBUGGER
      - DATABASE_URL
      - JWT_SECRET
    depends_on:
      - authenticated-api-db

  authenticated-api-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5429:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
