version: "3.7"
services:
  rabbit:
    image: rabbitmq:latest
    logging:
      driver: none

  fastapi:
    image: celery_simple:latest
    ports:
      - 8080:8080
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080

  worker:
    image: celery_simple:latest
    entrypoint: celery --app app.workers.calc worker -c 2 --loglevel=info
